name: nix flake check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = no-url-literals
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://ngi.cachix.org/
      - id: flake-show
        name: Obtain `nix flake show` output
        run: |
          sudo apt install colorized-logs
          echo 'output<<EOF' >> $GITHUB_OUTPUT
          nix flake show --all-systems | ansi2txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ```text
            ${{ steps.flake-show.outputs.output }}
            ```
      - run: nix ${{ runner.debug && '--debug --print-build-logs' }} flake check
