name: nix flake check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = no-url-literals
      - uses: cachix/cachix-action@v10
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          name: ngi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@main
        if: ${{ github.event.pull_request.head.repo.fork }}
        with:
          upstream-cache: https://ngi.cachix.org/
      - run: nix ${{ runner.debug && '--debug --print-build-logs' }} flake check
