name: nix flake update
on:
  workflow_dispatch:
  schedule:
    # Run at an odd time to avoid spikes at, e.g. midnight.
    # We don't really care too much about the particular time.
    # https://crontab.guru/#17_1_*_*_Mon
    - cron: '17 1 * * Mon' 

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v1
      - uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "flake: Update flake.lock"
          pr-labels: |
            automated
